from app.agents.base_agent import BaseAgent
from app.graph.state import ResumeState
from app.tools.job_search import search_google_jobs
from app.core.logger import get_logger

logger = get_logger(__name__)


class JobFetcherAgent(BaseAgent):
    """
    Generates job search query using LLM and immediately fetches jobs.
    """

    prompt_file = "job_query.yaml"

    def __init__(self) -> None:
        super().__init__()
        self._prompt = self._load_prompt()

    def run(self, state: ResumeState) -> dict:
        logger.info("JobRecommendationAgent started")

        if state.get("error"):
            logger.warning("Skipping — upstream error detected")
            return {}

        skills_analysis = state.get("skills_analysis", {}) or {}

        try:

            messages = self._build_messages(
                technical_skills=", ".join(skills_analysis.get("technical_skills", [])),
                tools_and_platforms=", ".join(
                    skills_analysis.get("tools_and_platforms", [])
                ),
                domains=", ".join(skills_analysis.get("domains", [])),
            )

            response = self.llm.invoke(messages)

            result = self._parse_json_response(response.content)
            query = result.get("query")

            if not query:
                raise ValueError("No query generated by LLM")

            logger.info(f"Generated job query: {query}")

            jobs = []

            domains = result.get("domains")

            for domain in domains[:3]:
                job = search_google_jobs.invoke({"query": domain})
                jobs.append(job)

            logger.info("Job search completed")

            return {"recommended_jobs": jobs}

        except Exception as exc:
            logger.exception("Job recommendation failed")
            raise exc
